import { db } from "@/lib/db";
import { emailThreads, emailMessages, userProfiles, agentActions } from "@/lib/db/schema";
import { eq, and, isNull } from "drizzle-orm";
import { classifyEmail } from "@/lib/agents/triage-agent";
import { generateDraft } from "@/lib/agents/draft-agent";
import { extractWritingStyle, type WritingStyle } from "@/lib/agents/tone-extractor";

export async function autoClassifyThreads(userId: string, businessType?: string): Promise<number> {
  const unclassified = await db
    .select()
    .from(emailThreads)
    .where(
      and(
        eq(emailThreads.userId, userId),
        isNull(emailThreads.classification)
      )
    );

  let classified = 0;
  const BATCH_SIZE = 5;

  for (let i = 0; i < unclassified.length; i += BATCH_SIZE) {
    const batch = unclassified.slice(i, i + BATCH_SIZE);
    const results = await Promise.allSettled(
      batch.map(async (thread) => {
        const messages = await db
          .select()
          .from(emailMessages)
          .where(eq(emailMessages.threadId, thread.id))
          .limit(1);

        const lastMsg = messages[messages.length - 1];

        const classification = await classifyEmail({
          subject: thread.subject ?? "",
          snippet: thread.snippet ?? "",
          senderEmail: lastMsg?.senderEmail ?? "",
          senderName: lastMsg?.senderName ?? null,
          messageCount: thread.messageCount ?? 1,
          direction: thread.lastMessageDirection ?? "inbound",
          businessType,
        });

        await db
          .update(emailThreads)
          .set({
            businessCategory: classification.businessCategory,
            urgency: classification.urgency,
            businessLeverage: classification.businessLeverage,
            currentState: classification.recommendedAction === "hide" ? "hidden" : "classified",
            agentObjective: classification.agentObjective,
            classification: classification as unknown as Record<string, unknown>,
            updatedAt: new Date(),
          })
          .where(eq(emailThreads.id, thread.id));

        return true;
      })
    );

    classified += results.filter((r) => r.status === "fulfilled").length;
    if (i + BATCH_SIZE < unclassified.length) {
      await new Promise((r) => setTimeout(r, 3000));
    }
  }

  return classified;
}

export async function extractUserTone(userId: string): Promise<WritingStyle | null> {
  const outboundMessages = await db
    .select({ bodyFull: emailMessages.bodyFull })
    .from(emailMessages)
    .innerJoin(emailThreads, eq(emailMessages.threadId, emailThreads.id))
    .where(
      and(
        eq(emailThreads.userId, userId),
        eq(emailMessages.direction, "outbound")
      )
    )
    .limit(20);

  const sentEmails = outboundMessages
    .map((m) => m.bodyFull)
    .filter((b): b is string => !!b && b.length > 30);

  if (sentEmails.length < 3) return null;

  const style = await extractWritingStyle(sentEmails);

  // Store in user profile
  await db
    .update(userProfiles)
    .set({
      onboardingAnswers: {
        ...(await db
          .select({ onboardingAnswers: userProfiles.onboardingAnswers })
          .from(userProfiles)
          .where(eq(userProfiles.id, userId))
          .limit(1)
          .then((r) => (r[0]?.onboardingAnswers as Record<string, unknown>) ?? {})),
        writingStyle: style,
      },
    })
    .where(eq(userProfiles.id, userId));

  return style;
}

export async function autoGenerateDrafts(userId: string): Promise<number> {
  const [user] = await db
    .select()
    .from(userProfiles)
    .where(eq(userProfiles.id, userId))
    .limit(1);

  const writingStyle = (user?.onboardingAnswers as Record<string, unknown>)?.writingStyle as WritingStyle | undefined;

  const draftThreads = await db
    .select()
    .from(emailThreads)
    .where(
      and(
        eq(emailThreads.userId, userId),
        eq(emailThreads.currentState, "classified")
      )
    );

  // Filter to threads where recommended action is draft_response
  const toDraft = draftThreads.filter((t) => {
    const classification = t.classification as Record<string, unknown> | null;
    return classification?.recommendedAction === "draft_response";
  });

  let drafted = 0;

  for (const thread of toDraft.slice(0, 10)) {
    try {
      const messages = await db
        .select()
        .from(emailMessages)
        .where(eq(emailMessages.threadId, thread.id));

      const styleContext = writingStyle
        ? `\n\nIMPORTANT - Match the founder's writing style exactly:
${writingStyle.summary}
Tone: ${writingStyle.tone}
Sign off: ${writingStyle.signOff}
Traits: ${writingStyle.traits.join(", ")}
NEVER use: ${writingStyle.avoidances.join(", ")}`
        : "\n\nWrite in a friendly, human tone. No em dashes. Sound informed and helpful.";

      const draft = await generateDraft({
        threadSubject: thread.subject ?? "",
        threadSnippet: thread.snippet ?? "",
        messageHistory: messages.map((m) => ({
          direction: m.direction,
          senderName: m.senderName,
          bodySummary: m.bodyFull ?? m.bodySummary,
          sentAt: m.sentAt?.toISOString() ?? null,
        })),
        classification: thread.classification as Record<string, string> | null,
        businessType: user?.businessType ?? undefined,
        founderName: user?.name ?? undefined,
        businessContext: styleContext,
      });

      await db.insert(agentActions).values({
        userId,
        threadId: thread.id,
        actionType: "auto_draft",
        agentName: "draft-agent",
        output: { draft } as Record<string, unknown>,
        status: "pending_review",
        modelUsed: "us.anthropic.claude-sonnet-4-6",
        createdAt: new Date(),
      });

      await db
        .update(emailThreads)
        .set({ currentState: "draft_ready", updatedAt: new Date() })
        .where(eq(emailThreads.id, thread.id));

      drafted++;
    } catch (err) {
      console.error(`Draft generation failed for thread ${thread.id}:`, err);
    }
  }

  return drafted;
}
