import "dotenv/config";

export const config = {
  google: {
    clientId: process.env.GOOGLE_CLIENT_ID,
    clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    refreshToken: process.env.GOOGLE_REFRESH_TOKEN,
    redirectUri: process.env.GOOGLE_REDIRECT_URI || "http://localhost:3000/api/auth/google/callback",
    sheetId: process.env.GOOGLE_SHEET_ID,
  },
  anishEmail: process.env.ANISH_EMAIL || "ak8686@princeton.edu",
  bedrock: {
    bearerToken: process.env.AWS_BEARER_TOKEN_BEDROCK,
    region: process.env.AWS_BEDROCK_REGION || "us-east-1",
  },
  timezone: process.env.TIMEZONE || "America/New_York",
  meeting: {
    durationMinutes: parseInt(process.env.MEETING_DURATION_MINUTES || "30", 10),
    windowStartHour: parseInt(process.env.WINDOW_START_HOUR || "17", 10),
    windowEndHour: parseInt(process.env.WINDOW_END_HOUR || "22", 10),
    horizonDays: parseInt(process.env.SCHEDULING_HORIZON_DAYS || "14", 10),
    allowedDays: (process.env.ALLOWED_DAYS || "0,1,2,3").split(",").map(Number),
  },
  fbFinder: {
    seedSearchTerms: [
      "bay area indian parents",
      "bay area parents college admissions",
      "high school parents college prep",
      "south asian parents education",
      "college admissions support parents",
      "high school extracurriculars",
      "SAT prep parents",
    ],
    classifierModel: process.env.FB_FINDER_CLASSIFIER_MODEL || "us.amazon.nova-micro-v1:0",
    classifierFallback: "us.amazon.nova-lite-v1:0",
    maxGroupsActive: parseInt(process.env.MAX_ACTIVE_GROUPS || "30", 10),
    groupsPerScrape: parseInt(process.env.FB_FINDER_GROUPS_PER_SCRAPE || "4", 10),
    maxScrollsPerGroup: parseInt(process.env.FB_FINDER_MAX_SCROLLS || "10", 10),
    maxScrollsPerKeyword: parseInt(process.env.FB_FINDER_MAX_SCROLLS_PER_KEYWORD || "4", 10),
    keywordsPerGroup: parseInt(process.env.FB_FINDER_KEYWORDS_PER_GROUP || "5", 10),
    maxPostAgeDays: parseInt(process.env.FB_FINDER_MAX_POST_AGE || "7", 10),
    cooldownMinutes: parseInt(process.env.FB_FINDER_COOLDOWN_MINUTES || "240", 10),
    minYieldRate: parseFloat(process.env.FB_FINDER_MIN_YIELD_RATE || "0.005"),
    exploreRatio: parseFloat(process.env.FB_FINDER_EXPLORE_RATIO || "0.25"),
    dailyLlmBudgetUsd: parseFloat(process.env.FB_FINDER_DAILY_BUDGET || "15.0"),
    minClassificationConfidence: parseFloat(process.env.FB_FINDER_MIN_CONFIDENCE || "0.7"),
    sessionDir: process.env.FB_SESSION_DIR || ".session/facebook",
    browserLockFile: "pipeline/.browser-lock",
    maxBrowsingMinutes: parseInt(process.env.FB_FINDER_MAX_BROWSING_MINUTES || "15", 10),
    quietHoursStart: parseInt(process.env.QUIET_HOURS_START || "2", 10),
    quietHoursEnd: parseInt(process.env.QUIET_HOURS_END || "6", 10),
    skipQuietHours: process.env.SKIP_QUIET_HOURS === "true",
    testMode: process.env.TEST_MODE === "true",
  },
};
